	#pragma config(Sensor, dgtl1,  button1,        sensorTouch)
	//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

	#define XAxisMotor1 port2
	#define XAxisMotor2 port3
	#define YAxisMotor  port4
	#define ZAxisMotor  port5
	#define Claw        port6                    //포트 정의

	#define XMotorSpeed1 2 
	#define XMotorSpeed2 2
	#define YMotorSpeed  2
	#define ZMotorSpeed  50             
	#define ClawSpeed    50                     //속도 정의              

	#define Runtime     30000            
	#define ZTime       1350                    //시간 정의

	void probability()
	{
		srand(nSysTime);                        //확률함수 시드=시스템 시간
	  unsigned int rand_num = (rand()%3)+1;     //rand_num=1,2,3 중 하나

	  switch(rand_num)
	  {
	  	case 1 :                               //놓는 경우1
	  	clearTimer(T1);
	  	 while(time1[T1]<100)
	  	 {
	  	     motor[Claw]=ClawSpeed;
	  	 }
	  	 break;
	  	case 2 :                              //놓는 경우 2
	  	clearTimer(T1);
	  	 while(time1[T1]<100)
	  	 {
	  	     motor[Claw]=ClawSpeed;
	  	 }
	  	break;
	  	case 3 :  break;                      //아무것도 안함
	  }

	}

	task main()
	{
	 wait:

	 string mainBattery;                     //배터리 잔량관련
	 bLCDBacklight=true;                     //LCD 관련
	 while(1)                           
	 {

	  clearLCDLine(0);
	  clearLCDLine(1);
 		displayLCDString(0, 0, "Battery: ");
	  sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V');
	  displayNextLCDString(mainBattery);    //LCD,배터리 관련 ¨

 		if(SensorValue(button1)==1)      //버튼==1(눌렸을 때)
		{
			goto start;                  //시작
		}
		else
		{
			//goto wait;                 
		}                                
	 }                                   
		start:

	  bLCDBacklight=true;                //LCD on

		clearTimer(T1);                  //시간 초기화
	  while(time1[T1]<Runtime)          
	  {
  		clearLCDLine(0);
  		clearLCDLine(1);
		  displayLCDPos(0,0);
  		displayNextLCDString("time left");
  		displayLCDPos(0,0);
  		displayNextLCDNumber(time1[T1]);   //남는시간 표시

		motor[XAxisMotor1]= -1*(vexRT[Ch3])/XMotorSpeed1; 
		motor[XAxisMotor2]= -1*(vexRT[Ch3])/XMotorSpeed2; 
		//x axis motor joystick
		motor[YAxisMotor]=vexRT[Ch4]/YMotorSpeed;
		//y axis motor joystick

		if(vexRT[Btn5U]==1)
		{
			clearTimer(T1);
			while (time1[T1]<ZTime)
			{
				motor[ZAxisMotor] = ZMotorSpeed;
			}
		}
		else if(vexRT[Btn5D]==1)
		{
			clearTimer(T1);
			while (time1[T1]<ZTime)
			{
				motor[ZAxisMotor] = -ZMotorSpeed;
			}
		}//claw control
		else if(vexRT[Btn6U]==1)
		{
		  motor[Claw]=ClawSpeed;
		  probability();
		}
		else if(vexRT[Btn6D]==1)
		{
    		motor[ZAxisMotor]=-ClawSpeed;
		}
		else                                    //무입력==무동작
		{
    				motor[Claw]=0;
    				motor[ZAxisMotor]=0;
		}
	  }
	  goto wait;                               //처음으로
	}
