 #pragma config(Sensor, dgtl1,  button1,        sensorTouch)
	//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

	#define XAxisMotor1 port2
	#define XAxisMotor2 port3
	#define YAxisMotor  port4
	#define ZAxisMotor  port5
	#define Claw        port6                    //모터 정의

	#define XMotorSpeed1 2
	#define XMotorSpeed2 2
	#define YMotorSpeed  2
	#define ZMotorSpeed  50
	#define ClawSpeed    50                     //속도 정의

	#define Runtime     30000
	#define ZTime       1350                    //시간 정의

	int random_num[2]={9826,0};

	void probability()
	{
	  byte translator=0;                  //확률 변환

		long constant1=5267, constant2=3904 ,divide=2^12; //divide=4096
		random_num[1]=(constant1*random_num[0]+constant2)%divide;    //확률(LCG)선형합동법

		if(0<=random_num<=1365)
		  translator=1;
		else if(1365<=random_num<=2730)
			translator=2;
	  else
	  	translator=3;

		switch(translator)
	  {
	  	case 1 :                               //집게 살짝 놓기
	  	clearTimer(T1);
	  	 while(time1[T1]<250)

	  	 {
	  	     motor[Claw]=-ClawSpeed;
	  	 }
	  	 break;
	  	case 2 :                              //집게 살짝 놓기 2
	  	clearTimer(T1);
	  	 while(time1[T1]<250)
	  	 {
	  	     motor[Claw]=-ClawSpeed;
	  	 }
	  	break;
	  	case 3 :  break;                      //무행동
          }

		random_num[0] = random_num[1];

	}

	task main()
	{
	 wait:

	 string mainBattery;                     //배터리
	 bLCDBacklight=true;                     //LCD 
	 while(1)
	 {

	  clearLCDLine(0);
	  clearLCDLine(1);
 	  displayLCDString(0, 0, "Battery: ");
	  sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V');
	  displayNextLCDString(mainBattery);    //LCD, 배터리잔량

 		if(SensorValue(button1)==1)      //버튼센서 눌리면 시작
		{
			goto start;                  
		}
		else
	 }
		start:

	  bLCDBacklight=true;                //LCD on

		clearTimer(T1);                  //가동시간 초기화
	  while(time1[T1]<Runtime)
	  {
  		clearLCDLine(0);
  		clearLCDLine(1);
		  displayLCDPos(0,0);
  		displayNextLCDString("time left");
  		displayLCDPos(0,0);
  		displayNextLCDNumber((30000-time1[T1])/1000);   //남은시간

		motor[XAxisMotor1]= -1*(vexRT[Ch3])/XMotorSpeed1;
		motor[XAxisMotor2]= -1*(vexRT[Ch3])/XMotorSpeed2;
		//x axis motor joystick
		motor[YAxisMotor]=vexRT[Ch4]/YMotorSpeed;
		//y axis motor joystick

		if(vexRT[Btn5U]==1)
		{
			clearTimer(T1);
			while (time1[T1]<ZTime)
			{
				motor[ZAxisMotor] = ZMotorSpeed;
			}
		}
		else if(vexRT[Btn5D]==1)
		{
			clearTimer(T1);
			while (time1[T1]<ZTime)
			{
				motor[ZAxisMotor] = -ZMotorSpeed;
			}
		}//claw control
		else if(vexRT[Btn6U]==1)
		{
		  motor[Claw]=ClawSpeed;
		  probability();                   //확률함수
		}
		else if(vexRT[Btn6D]==1)
		{
    		motor[ZAxisMotor]=-ClawSpeed;
		}
		else                                    //무입력==무동작
		{
    				motor[Claw]=0;
    				motor[ZAxisMotor]=0;
		}
	  }
	  goto wait;                               //처음으로
}
